### cookie 修改 http-client.env.json 配置文件中的即可
### 删除 theme 配置， Cookit 可以从 Console 后台 F12 获取，删除后，在后台将看不到主题
DELETE http://localhost:8090/apis/theme.halo.run/v1alpha1/themes/theme-hao-setting
Content-Type: application/json
Cookie: {{cookie}}


### 设置主题, body 即为 theme.yaml 的内容转 json，以下是theme-hao主题示例

POST http://localhost:8090/apis/theme.halo.run/v1alpha1/themes
Content-Type: application/json
Cookie: {{cookie}}

{
  "apiVersion": "theme.halo.run/v1alpha1",
  "kind": "Theme",
  "metadata": {
    "name": "theme-hao"
  },
  "spec": {
    "displayName": "Hao",
    "author": {
      "name": "程序员小航",
      "website": "https://liuzhihang.com"
    },
    "description": "Halo 2.0 Theme base on Thymeleaf, Referring to Butterfly and Heo",
    "logo": "https://liuzhihang.com/logo",
    "website": "https://liuzhihang.com",
    "repo": "https://github.com/liuzhihang/halo-theme-hao",
    "settingName": "theme-hao-setting",
    "configMapName": "theme-hao-configMap",
    "version": "1.0.0",
    "require": "2.0.0"
  }
}